### ISSUE TITLE
Lighten transparency on hero/header vignetting...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/ur-super-theme#8]
This is too dark. Also add slight drop shadow to hero text if need be.

**Comment by jasonmarkle** [comment]
You may want to consider adding more steps to the gradient. `radial-gradient(farthest-side at 90% 55%, transparent, transparent, transparent, transparent, #000)` will significantly add lightness without losing the actual vignette to much. I believe, you can add as many steps as you need, and you subsequently will require less of a jump on the opacity.

Here's a before:

![Before](https://cloud.githubusercontent.com/assets/5209650/15084464/a54bcc3c-13a1-11e6-9c18-9359218d3128.png) 

and after additional transparent steps:

![After additional Transparent steps](https://cloud.githubusercontent.com/assets/5209650/15084465/a54d4684-13a1-11e6-8c3a-990b8a7fdc7d.png)


and after additional transparent steps with the opacity dropped by 20%:

![After additional Transparent steps and 20% opacity drop](https://cloud.githubusercontent.com/assets/5209650/15084554/2cc381fa-13a2-11e6-8708-1cfda560501a.png)

The additional steps gives you a more drastic change, so you may want to just keep adding steps till you get close to where you want to be within value, then adjust opacity to get the vignetting as light/dark as you need it to be.
